
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_SEGUN = 41;
  public static final int R_HACER = 42;
  public static final int R_CONPARAMETROS = 58;
  public static final int R_INCREMENTO = 47;
  public static final int CORCHETE_I = 9;
  public static final int R_FINSI = 40;
  public static final int DIFERENTE = 30;
  public static final int RESTA = 17;
  public static final int R_REPETIR = 51;
  public static final int R_CON = 46;
  public static final int R_PARA = 44;
  public static final int CORCHETE_D = 10;
  public static final int VALUE_STRING = 12;
  public static final int R_NUMBER = 65;
  public static final int R_FINSEGUN = 43;
  public static final int R_DELOCONTRARIO = 38;
  public static final int R_INGRESAR = 33;
  public static final int NOT = 24;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int R_RETORNAR = 53;
  public static final int VALUE_NUMERO = 11;
  public static final int R_CHAR = 63;
  public static final int VALUE_CHAR = 13;
  public static final int SUMA = 16;
  public static final int R_FINMETODO = 59;
  public static final int R_EJECUTAR = 54;
  public static final int MAYOR_O = 27;
  public static final int R_STRING = 62;
  public static final int EOF = 0;
  public static final int PRODUCTO = 18;
  public static final int R_HASTA = 45;
  public static final int R_FUNCION = 60;
  public static final int R_INICIO = 31;
  public static final int R_FINFUNCION = 61;
  public static final int R_IMPRIMIRLN = 56;
  public static final int error = 1;
  public static final int MENOR_O = 28;
  public static final int COMA = 8;
  public static final int R_OSI = 39;
  public static final int INTERROGANTE_I = 5;
  public static final int MODULO = 20;
  public static final int MENOR = 26;
  public static final int R_IMPRIMIR = 55;
  public static final int INTERROGANTE_D = 6;
  public static final int VALUE_ID = 15;
  public static final int MAYOR = 25;
  public static final int POTENCIA = 21;
  public static final int R_ENTONCES = 37;
  public static final int R_BOOL = 64;
  public static final int PARENTESIS_I = 2;
  public static final int FLECHA = 4;
  public static final int VALUE_BOOL = 14;
  public static final int R_COMO = 34;
  public static final int PARENTESIS_D = 3;
  public static final int R_FINPARA = 48;
  public static final int PTO_COMA = 7;
  public static final int R_METODO = 57;
  public static final int R_SI = 36;
  public static final int R_FIN = 32;
  public static final int R_MIENTRAS = 49;
  public static final int R_CONVALOR = 35;
  public static final int DIVISION = 19;
  public static final int ES_IGUAL = 29;
  public static final int R_HASTAQUE = 52;
  public static final int R_FINMIENTRAS = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_I",
  "PARENTESIS_D",
  "FLECHA",
  "INTERROGANTE_I",
  "INTERROGANTE_D",
  "PTO_COMA",
  "COMA",
  "CORCHETE_I",
  "CORCHETE_D",
  "VALUE_NUMERO",
  "VALUE_STRING",
  "VALUE_CHAR",
  "VALUE_BOOL",
  "VALUE_ID",
  "SUMA",
  "RESTA",
  "PRODUCTO",
  "DIVISION",
  "MODULO",
  "POTENCIA",
  "AND",
  "OR",
  "NOT",
  "MAYOR",
  "MENOR",
  "MAYOR_O",
  "MENOR_O",
  "ES_IGUAL",
  "DIFERENTE",
  "R_INICIO",
  "R_FIN",
  "R_INGRESAR",
  "R_COMO",
  "R_CONVALOR",
  "R_SI",
  "R_ENTONCES",
  "R_DELOCONTRARIO",
  "R_OSI",
  "R_FINSI",
  "R_SEGUN",
  "R_HACER",
  "R_FINSEGUN",
  "R_PARA",
  "R_HASTA",
  "R_CON",
  "R_INCREMENTO",
  "R_FINPARA",
  "R_MIENTRAS",
  "R_FINMIENTRAS",
  "R_REPETIR",
  "R_HASTAQUE",
  "R_RETORNAR",
  "R_EJECUTAR",
  "R_IMPRIMIR",
  "R_IMPRIMIRLN",
  "R_METODO",
  "R_CONPARAMETROS",
  "R_FINMETODO",
  "R_FUNCION",
  "R_FINFUNCION",
  "R_STRING",
  "R_CHAR",
  "R_BOOL",
  "R_NUMBER"
  };
}

